### ISSUE TITLE
Cannot find module 'underscore-keypath'

### ISSUE THREAD

**Issue by drkno** [crobays/require-install#5]
New installs (old ones work fine) of `require-install` from npm throw an exception when attempting to install a package.

A very quick example of something that would cause this exception:

```
var r = require('require-install');
r('express');
```

The above example will result in the following exception:

```
Error: Cannot find module 'underscore-keypath'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/mk/dev/node_modules/require-install/node_modules/dot-json/lib/dot-json.js:3:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
```

**Comment by maikelvl** [comment]
I'm not able to reproduce this on node 0.12.9, 4.2.6 and 5.6.0. Could you try to remove the node_modules completely and retry?

**Comment by drkno** [comment]
Failure occurs on node 5.0 (win) and node 4.2.1 (osx), on a fresh install. I'll gather more data soon when I have more time.
